name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: kinetic,  ROS_REPO: testing}
          - {ROS_DISTRO: kinetic,  ROS_REPO: main}
          - {ROS_DISTRO: melodic,  ROS_REPO: testing}
          - {ROS_DISTRO: melodic,  ROS_REPO: main}
          - {ROS_DISTRO: noetic,   ROS_REPO: testing}
          - {ROS_DISTRO: noetic,   ROS_REPO: main}
          - {ROS_DISTRO: dashing,  ROS_REPO: testing}
          - {ROS_DISTRO: dashing,  ROS_REPO: main}
          - {ROS_DISTRO: eloquent, ROS_REPO: testing}
          - {ROS_DISTRO: eloquent, ROS_REPO: main}
          - {ROS_DISTRO: foxy,     ROS_REPO: testing}
          - {ROS_DISTRO: foxy,     ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
